name: Continue on error
on: push
jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
      - run: echo "This step will run even if the previous step fails and exits on success"
