name: Flow control
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: exit "$(( RANDOM % 2 ))"
      # execute if previous step success and this step must be failure
      - run: exit 1
        if: error
      - run: echo "Catch error step"
        if: ${{ failure() && steps.error.outcome == 'failure' }}
