name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: "Greeting message"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "${{ github.event.inputs.greeting }}"
