name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      # for create release note
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      # build application
      - run: |
          go build -ldflags "-X main.version=${VERSION}" \
            -o "${RUNNER_TEMP}/example" go/example/main.go
      # create release note
      - run: |
          gh release create "${VERSION}" -t "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "${RUNNER_TEMP}/example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
