name: Reusable workflows
on:
  workflow_call:
    inputs:
      pr-number:
        type: string
        default: ${{ github.event.pull_request.number }}
        required: false
        description: "The PR number to use for the workflow run"
    secrets:
      token:
        required: true
        description: "The token to use for the workflow run"
    outputs:
      message:
        value: ${{ jobs.comment.outputs.pr-comment }}
        description: "The comment message to use for the workflow run"
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: pr-comment
        run: |
          body="Welcome, ${GITHUB_ACTOR}!"
          gh pr comment "${PR_NUMBER}" -b "$body"
          echo "body=${body}" >> "${GITHUB_OUTPUT}"
        env:
          PR_NUMBER: ${{ github.event.inputs.pr-number }}
          GITHUB_TOKEN: ${{ secrets.token }}
    outputs:
      pr-comment: ${{ steps.pr-comment.outputs.body }}
