name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.MY_SUPER_SECRET }}
    steps:
      # it must be masked in the logs
      - run: echo "${SECRET}"
      # it must NOT be masked in the logs
      - run: echo "${SECRET:0:1} ${SECRET#?}"
